#!/bin/bash

# install java

apt-get update
apt-get install curl

cd ~
curl -O https://download.java.net/java/GA/jdk16.0.2/d4a915d82b4c4fbb9bde534da945d746/7/GPL/openjdk-16.0.2_linux-x64_bin.tar.gz
tar -xvf openjdk-16.0.2_linux-x64_bin.tar.gz
mv jdk-16.0.2 /opt/
vi /root/.bashrc
export JAVA_HOME=/opt/jdk-16.0.2
export PATH=$PATH:$JAVA_HOME/bin
export CALSS_PATH=$CLASS_PATH:$JAVA_HOME/lib 

source ~/.bashrc

java -version